
export const INPUT_SAMPLE_RATE = 16000;
export const OUTPUT_SAMPLE_RATE = 24000;
export const MIC_BUFFER_SIZE = 4096;
export const DEFAULT_ROTATION_INTERVAL_MS = 3000;
export const DEFAULT_TRANSITION_DURATION_MS = 3000;
